#!/bin/bash

# Define the project root directory relative to this script location
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Change into the build directory
cd "${PROJECT_ROOT}/build" || exit

# Configure the project where source is in the parent directory
cmake ..

# Clean and build the project
# Note: Using cmake --build allows for a more portable script across different platforms and generators
# cmake --build . --target clean

make clean
make

# Return to the project root directory to run the executable
cd ..

# Execute the main program
./main ../model/box_aruco.xml

# Uncomment to debug the main program using lldb
# lldb ./main -- ../model/box.xml
