#!/bin/bash

# Define the project root directory
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Create the build directory if it doesn't exist
mkdir -p "${PROJECT_ROOT}/build"
cd "${PROJECT_ROOT}/build" || exit 1

# Run CMake to configure the project
cmake .. || { echo "CMake configuration failed!"; exit 1; }

# Build the project
make || { echo "Build failed!"; exit 1; }

# Go back to the project root
cd "${PROJECT_ROOT}" || exit 1

# Run the compiled program
./build/main ../model/differential_drive_car.xml

# Debug the program using lldb
# lldb ./build/main -- ../model/differential_drive_car.xml
