#!/bin/bash

# Configure the project where source is in the parent directory
cmake .

make clean
make

# Execute the main program
./add_borders ../model/asset/5x5_1000-0.png

# Uncomment to debug the main program using lldb
# lldb ./main -- ../model/asset/5x5_1000-0.png
